# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUaEnQsrjfcauH1a6q_-vPCGA4qXYIJG
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import pandas as pd
# import statsmodels.formula.api as smf
# from flask import Flask, request, jsonify
# 
# app = Flask(__name__)
# 
# cars = pd.read_csv("cars.csv")
# 
# model = smf.ols('MPG ~ VOL + SP + HP', data=cars).fit()
# 
# @app.route('/')
# def home():
#     return "Multilinear Regression Model is Live"
# 
# @app.route('/predict', methods=['POST'])
# def predict():
#     data = request.json
#     df = pd.DataFrame([data])
#     result = model.predict(df)
#     return jsonify({"Predicted_MPG": float(result)})
# 
# if __name__ == "__main__":
#     app.run()
#