# -*- coding: utf-8 -*-
"""requirements

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYl-L9McsxWaNqxtEsI7fv3tABXrHcJQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# flask
# pandas
# numpy
# statsmodels
# scikit-learn
# scipy
# matplotlib
# seaborn
#